$(document).ready(function(){
	$('.fav-tog').click(function(){
		$('#favourites').addClass('open-fav'); 
		$('#main-page').addClass('pause-page');
	}); 
	$('.body').click(function(){
		$('#main-page').removeClass('pause-page');
		$('#favourites').removeClass('open-fav');
	});
})